[2025-04-13T23:23:22.949+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T23:23:22.955+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: visitor_labels_etl_pipeline.extract_visitor_data manual__2025-04-13T15:19:42.944472+00:00 [queued]>
[2025-04-13T23:23:22.959+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: visitor_labels_etl_pipeline.extract_visitor_data manual__2025-04-13T15:19:42.944472+00:00 [queued]>
[2025-04-13T23:23:22.959+0800] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-04-13T23:23:22.975+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_visitor_data> on 2025-04-13 15:19:42.944472+00:00
[2025-04-13T23:23:22.978+0800] {standard_task_runner.py:72} INFO - Started process 85956 to run task
[2025-04-13T23:23:22.982+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'visitor_labels_etl_pipeline', 'extract_visitor_data', 'manual__2025-04-13T15:19:42.944472+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/labels_dag.py', '--cfg-path', '/tmp/tmpj_hcr64d']
[2025-04-13T23:23:22.982+0800] {standard_task_runner.py:105} INFO - Job 29: Subtask extract_visitor_data
[2025-04-13T23:23:23.019+0800] {task_command.py:467} INFO - Running <TaskInstance: visitor_labels_etl_pipeline.extract_visitor_data manual__2025-04-13T15:19:42.944472+00:00 [running]> on host Conglaptop.
[2025-04-13T23:23:23.064+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='visitor_labels_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_visitor_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T15:19:42.944472+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-13T15:19:42.944472+00:00'
[2025-04-13T23:23:23.065+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T23:23:23.066+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T23:23:23.066+0800] {logging_mixin.py:190} INFO - Current task name:extract_visitor_data state:running start_date:2025-04-13 15:23:22.955815+00:00
[2025-04-13T23:23:23.066+0800] {logging_mixin.py:190} INFO - Dag name:visitor_labels_etl_pipeline and current dag run status:running
[2025-04-13T23:23:23.066+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T23:23:23.066+0800] {logging_mixin.py:190} INFO - Starting visitor data extraction
[2025-04-13T23:23:23.067+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/airflow/dags/labels_dag.py", line 65, in extract_visitor_data
    scraper = VisitorScraper()
              ^^^^^^^^^^^^^^^^
TypeError: VisitorScraper.__init__() missing 1 required positional argument: 'historical_data'
[2025-04-13T23:23:23.071+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-13T23:23:23.071+0800] {logging_mixin.py:190} INFO - Task start:2025-04-13 15:23:22.955815+00:00 end:2025-04-13 15:23:23.071278+00:00 duration:0.115463
[2025-04-13T23:23:23.072+0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_visitor_data> dag:<DAG: visitor_labels_etl_pipeline> dagrun:<DagRun visitor_labels_etl_pipeline @ 2025-04-13 15:19:42.944472+00:00: manual__2025-04-13T15:19:42.944472+00:00, state:running, queued_at: 2025-04-13 15:23:19.980187+00:00. externally triggered: True>
[2025-04-13T23:23:23.072+0800] {logging_mixin.py:190} INFO - Failure caused by VisitorScraper.__init__() missing 1 required positional argument: 'historical_data'
[2025-04-13T23:23:23.072+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=visitor_labels_etl_pipeline, task_id=extract_visitor_data, run_id=manual__2025-04-13T15:19:42.944472+00:00, execution_date=20250413T151942, start_date=20250413T152322, end_date=20250413T152323
[2025-04-13T23:23:23.095+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T23:23:23.095+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task extract_visitor_data (VisitorScraper.__init__() missing 1 required positional argument: 'historical_data'; 85956)
Traceback (most recent call last):
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/.venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rencongchia/Y3S2/BT4301/project/airflow/dags/labels_dag.py", line 65, in extract_visitor_data
    scraper = VisitorScraper()
              ^^^^^^^^^^^^^^^^
TypeError: VisitorScraper.__init__() missing 1 required positional argument: 'historical_data'
[2025-04-13T23:23:23.115+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-13T23:23:23.125+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T23:23:23.126+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
